### ISSUE TITLE
Change propType of Select field (options/choices) to array, as it gives an error for any form that includes a drop down

### ISSUE THREAD

**Issue by shalawkarim** [robmarshall/gatsby-plugin-gravity-forms#4]
I have a multi-step form that includes lots of **dropdowns**, that is _<select><options>_ fields. However, for some reason, the Select field propTypes is given the propType of string, while it should be an array. That makes the Gatsby to given an error like

Error in function _.Select [as constructor] in ./node_modules/gatsby-plugin-gravity-forms/src/components/Select/index.js:11
Unexpected token o in JSON at position 1
   9 | const Select = ({ fieldData, name, ...wrapProps }) => {
  10 |   const {choices, cssClass, isRequired, size } = fieldData;
> 11 |   const options = JSON.parse(choices)
     |                       ^
  12 |
  13 |   const {
  14 |     register,

When you open the console, there is a better explanation:

`debug.module.js:1 Failed prop type: Invalid prop `fieldData.choices` of type `array` supplied to `Select`, expected `string`

looking at the node_modules for the plugin, we can see this, which I assume to be the problem, that the type of choices is a string instead of an array:

```
Select.propTypes = {
  fieldData: PropTypes.shape({
    choices: PropTypes.string,
    cssClass: PropTypes.string,
    isRequired: PropTypes.bool,
    size: PropTypes.string,
  }),
  register: PropTypes.func,
  wrapProps: PropTypes.object,
};
```

Please resolve that problem, I'll try to make the plugin to be local and correct the problem.

**Comment by embergardens** [comment]
@shalawkarim @robmarshall - I was able to resolve this by removing the JSON parse and switching the prop type to array: https://github.com/embergardens/gatsby-plugin-gravity-forms-eg/blob/select-fix/src/components/Select/index.js

Unclear where the shift from outputting array instead of string came from however.
